site_name: klein
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: 'teal'
    accent: 'deep orange'
  favicon: 'img/favicon.ico'
  feature:
    tabs: false
  logo:
    icon: 'flip'
site_url: https://jeremyong.com/klein/
repo_url: https://github.com/jeremyong/klein/
edit_uri: ''
repo_name: 'jeremyong/klein'
site_description: Klein - Realtime Projective Geometric Algebra
site_author: Jeremy Ong
copyright: 'Klein Copyright &copy; 2020 Jeremy Ong'
google_analytics: ['UA-10576233-1', 'auto']

plugins:
  - search

nav:
  - 'Home': 'index.md'
  - 'Quick Start': 'quickstart.md'
  - 'API':
      - 'Overview': 'overview.md'
      - 'GPU Support': 'gpu.md'
      - 'Plane': 'api/plane.md'
      - 'Lines': 'api/lines.md'
      - 'Point': 'api/point.md'
      - 'Direction': 'api/dir.md'
      - 'Rotor': 'api/rotor.md'
      - 'Translator': 'api/translator.md'
      - 'Motor': 'api/motor.md'
      - 'Geometric Product': 'api/gp.md'
      - 'Exterior Product': 'api/ext.md'
      - 'Poincare Dual': 'api/dual.md'
      - 'Regressive Product': 'api/reg.md'
      - 'Inner Product': 'api/dot.md'
      - 'Exponential/Logarithm': 'api/exp_log.md'
      - 'Projections': 'api/proj.md'
      - 'Dual Numbers': 'api/dualn.md'
  - 'Geometry Potpourri': 'geometry-potpourri.md'
  - 'Tutorial':
      - 'Introduction': 'tutorial/intro.md'
      - 'Exterior Algebra': 'tutorial/exterior_algebra.md'
  - 'Case Studies':
      - 'Basic Skeletal Animation': 'case_studies/ga_skeletal_animation.md'
  - 'Klein Shell': 'shell.md'
  - 'Performance': 'perf.md'
  - 'Discord': 'discord.md'
  - 'References': 'references.md'

extra_css:
  - 'css/extra.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css'

extra_javascript:
  - 'js/extra.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/ganja.js@1.0.169'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - pymdownx.arithmatex:
      generic: True
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.extrarawhtml
  - toc
  - sane_lists

extra:
  social:
    - type: 'github'
      link: 'https://github.com/jeremyong'
    - type: 'twitter'
      link: 'https://twitter.com/m_ninepoints'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jeremycong'
